--- 

- name: Setup server
  hosts: all
  become: true # become sudo
  pre_tasks:
    - name: "apt-get update"
      raw: apt-get update -qq
  roles:
    - general

- name: Computing setup
  hosts: web:mob-dev
  become: true
  roles:
    - node
    - chrome
    - sublime

- name: LAMP stack
  hosts: web
  become: true
  roles:
    - apache
    - mysql
    - php
    - web-building-setup

- name: mob dev project
  hosts: web
  become: true
  roles:
    - mob-dev-setup
